version: '3.8'

services:
  # Jenkins CI 서버
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-cicd
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - cicd-network

  # ArgoCD 서버
  argocd-server:
    image: quay.io/argoproj/argocd:latest
    container_name: argocd-server
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "8082:8443"
    command:
      - argocd-server
      - --insecure
    environment:
      - ARGOCD_SERVER_INSECURE=true
    volumes:
      - argocd_data:/home/argocd
    networks:
      - cicd-network

  # ArgoCD Repository Server
  argocd-repo-server:
    image: quay.io/argoproj/argocd:latest
    container_name: argocd-repo-server
    restart: unless-stopped
    command:
      - argocd-repo-server
    volumes:
      - argocd_data:/home/argocd
    networks:
      - cicd-network

  # ArgoCD Application Controller
  argocd-application-controller:
    image: quay.io/argoproj/argocd:latest
    container_name: argocd-application-controller
    restart: unless-stopped
    command:
      - argocd-application-controller
    volumes:
      - argocd_data:/home/argocd
    networks:
      - cicd-network

  # Redis (ArgoCD용)
  redis:
    image: redis:7-alpine
    container_name: argocd-redis
    restart: unless-stopped
    networks:
      - cicd-network

  # GitOps Repository (Gitea)
  gitea:
    image: gitea/gitea:latest
    container_name: gitops-repo
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea_data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
    networks:
      - cicd-network

volumes:
  jenkins_home:
  argocd_data:
  gitea_data:

networks:
  cicd-network:
    driver: bridge